# Generated by Django 3.1.4 on 2020-12-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrusers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField()),
                ('hr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrusers.hraccounts')),
            ],
        ),
    ]
